# Generated by Django 5.1.4 on 2025-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttraining',
            options={'verbose_name_plural': 'Product Trainings'},
        ),
        migrations.RemoveField(
            model_name='producttraining',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='producttraining',
            name='featured_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Featured Image URL'),
        ),
    ]
