# Generated by Django 5.1.4 on 2025-04-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0003_categories_producttraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Scroll_image',
            field=models.ImageField(null=True, upload_to='Media/fetured_img'),
        ),
        migrations.AlterField(
            model_name='producttraining',
            name='featured_video',
            field=models.FileField(null=True, upload_to='Media/videos'),
        ),
    ]
