# Generated by Django 5.1.4 on 2025-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0005_joiningapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningapplication',
            name='middle_name',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='joiningapplication',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joiningapplication',
            name='qualification_proof',
            field=models.FileField(default=0, upload_to='qualification_proofs/'),
            preserve_default=False,
        ),
    ]
