# Generated by Django 5.1.4 on 2025-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0006_joiningapplication_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joiningapplication',
            name='mobile_number',
            field=models.CharField(default='Not Provided', max_length=10),
        ),
    ]
