# Generated by Django 5.1.4 on 2025-04-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0007_alter_joiningapplication_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joiningapplication',
            name='qualification_proof',
        ),
        migrations.RemoveField(
            model_name='joiningapplication',
            name='submission_date',
        ),
        migrations.AlterField(
            model_name='joiningapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='joiningapplication',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='QualificationProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='qualification_proofs/')),
                ('joining_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_proofs', to='jango_app.joiningapplication')),
            ],
        ),
    ]
