# Generated by Django 5.1.4 on 2025-04-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0008_remove_joiningapplication_qualification_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
