# Generated by Django 5.1.4 on 2025-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0010_territory_tourplan_userterritory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userterritory',
            name='territory',
            field=models.CharField(max_length=255),
        ),
    ]
