# Generated by Django 5.1.4 on 2025-05-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0011_alter_userterritory_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jango_app.territory'),
        ),
        migrations.AlterField(
            model_name='userterritory',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jango_app.territory'),
        ),
    ]
