# Generated by Django 5.1.4 on 2025-05-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0012_profile_territory_alter_userterritory_territory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='territory',
        ),
        migrations.AddField(
            model_name='profile',
            name='territories',
            field=models.ManyToManyField(blank=True, to='jango_app.territory'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
