# Generated by Django 5.1.4 on 2025-05-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0013_remove_profile_territory_profile_territories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourplan',
            name='created_at',
        ),
    ]
