# Generated by Django 5.1.4 on 2025-05-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0015_question_answer_userquizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttraining',
            name='featured_video',
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(null=True, upload_to='Media/product_videos')),
                ('order', models.IntegerField(default=0)),
                ('product_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='jango_app.producttraining')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
