# Generated by Django 5.1.4 on 2025-05-12 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0016_remove_producttraining_featured_video_productvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='VideoAnswer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='VideoQuestion',
        ),
        migrations.RemoveField(
            model_name='videoquestion',
            name='training',
        ),
        migrations.AddField(
            model_name='videoquestion',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jango_app.productvideo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserVideoQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('attempted_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jango_app.productvideo')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.DeleteModel(
            name='UserQuizResult',
        ),
    ]
