# Generated by Django 5.1.4 on 2025-05-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0017_rename_answer_videoanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoquestion',
            name='product_training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_questions', to='jango_app.producttraining'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uservideoquizresult',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jango_app.productvideo'),
        ),
        migrations.AlterField(
            model_name='videoquestion',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
    ]
