# Generated by Django 5.1.4 on 2025-05-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0018_videoquestion_product_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoquestion',
            name='product_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_questions', to='jango_app.producttraining'),
        ),
    ]
