# Generated by Django 5.1.4 on 2025-05-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0020_alter_categories_options_categories_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideoquizresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
