# Generated by Django 5.1.4 on 2025-06-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0022_uservideounlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='productvideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
