# Generated by Django 5.1.4 on 2025-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0023_remove_productvideo_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Scroll_image',
        ),
        migrations.AddField(
            model_name='post',
            name='Scroll_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
