# Generated by Django 5.1.4 on 2025-07-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0024_remove_post_scroll_image_post_scroll_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Scroll_image_url',
        ),
    ]
