# Generated by Django 5.1.4 on 2025-07-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0025_remove_post_scroll_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Scroll_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
