# Generated by Django 5.1.4 on 2025-07-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0026_post_scroll_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='joiningapplication',
            options={'verbose_name_plural': 'Joining Applications'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='producttraining',
            options={'verbose_name_plural': 'Product Trainings'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['order'], 'verbose_name_plural': 'Product Videos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='qualificationproof',
            options={'verbose_name_plural': 'Qualification Proofs'},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name_plural': 'Territories'},
        ),
        migrations.AlterModelOptions(
            name='tourplan',
            options={'verbose_name_plural': 'Tour Plans'},
        ),
        migrations.AlterModelOptions(
            name='userterritory',
            options={'verbose_name_plural': 'User Territories'},
        ),
        migrations.AlterModelOptions(
            name='uservideoquizresult',
            options={'verbose_name_plural': 'User Video Quiz Results'},
        ),
        migrations.AlterModelOptions(
            name='videoanswer',
            options={'verbose_name_plural': 'Video Answers'},
        ),
        migrations.AlterModelOptions(
            name='videoquestion',
            options={'verbose_name_plural': 'Video Questions'},
        ),
        migrations.RemoveField(
            model_name='producttraining',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='qualificationproof',
            name='file',
        ),
        migrations.AddField(
            model_name='producttraining',
            name='featured_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Featured Image URL'),
        ),
        migrations.AddField(
            model_name='qualificationproof',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Scroll_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Scroll Image URL'),
        ),
    ]
