# Generated by Django 5.1.4 on 2025-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0027_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='joiningapplication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producttraining',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='qualificationproof',
            options={},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tourplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userterritory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uservideoquizresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='videoanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='videoquestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='producttraining',
            name='featured_image_url',
        ),
        migrations.RemoveField(
            model_name='qualificationproof',
            name='file_url',
        ),
        migrations.AddField(
            model_name='producttraining',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='Media/fetured_img'),
        ),
        migrations.AddField(
            model_name='qualificationproof',
            name='file',
            field=models.FileField(default='', upload_to='qualification_proofs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='Scroll_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
