# Generated by Django 5.1.4 on 2025-07-25 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0028_alter_categories_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationproof',
            name='qualification',
            field=models.CharField(default='Default Qualification', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualificationproof',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='Default Qualification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualificationproof',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualificationproof',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='qualification_proofs/'),
        ),
        migrations.AlterField(
            model_name='qualificationproof',
            name='joining_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_proofs', to='jango_app.joiningapplication'),
        ),
    ]
